version: '3.7'

services:
  reverse-proxy:
    image: library/traefik:v2.2
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: api
    ports:
    - 8080
    env_file:
      - .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`localhost`)

  nats:
    image: library/nats:2.1-linux
    ports:
    - 4222
    - 8222
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.subscriber.rule=Host(`nats.local`)


  subscriber:
    build:
      context: subscriber
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.subscriber.rule=Host(`sub.local`)


  #whoami:
  #  image: containous/whoami
  #  labels:
  #   - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"