version: '3.7'

services:

  api:
    build:
      context: api
    ports:
    - 8080:8080
    depends_on:
      - nats-server
      - nats-streaming-server
    env_file:
      - .env
    restart: always

  subscriber:
    build:
      context: subscriber
    depends_on:
      - nats-server
      - nats-streaming-server
    env_file:
      - .env
    restart: always

  nats-server:
    image: library/nats:2.1.9-alpine
    hostname: nats-server
    container_name: nats-server
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222


  nats-streaming-server:
    image: library/nats-streaming:0.19.0-alpine
    hostname: nats-streaming-server
    container_name: nats-streaming-server
    restart: always
    depends_on:
      - nats-server
    command: nats-streaming-server --nats_server nats://nats-server:4222


  #whoami:
  #  image: containous/whoami
  #  labels:
  #   - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"